version: 2.1
orbs:
  python: circleci/python@3.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          command: |
            pip install unittest-xml-reporting
            python -m xmlrunner discover -s . -p 'test_classifyTriangles.py' -o test-results
      - store_test_results:
          path: test-results

workflows:
  testing_triangles:
    jobs:
      - build-and-test
